### ISSUE TITLE
Merging streams doesn't work as of `0.9.0`

### ISSUE THREAD

**Issue by dtothefp** [assemble/assemble-streams#3]
https://github.com/assemble/assemble-core/issues/10

@doowb suggested
```
return src(stream).pipe(handle(this, 'onStream'));` to `return src(stream.pipe(handle(this, 'onStream')));
```

**Comment by doowb** [comment]
Making the fix now.

**Comment by doowb** [comment]
Fixed in `0.4.1` and published. Thanks @dtothefp.

**Comment by jonschlinkert** [comment]
nice work @doowb! thanks for reporting the issue @dtothefp

**Comment by dtothefp** [comment]
Thanks for the help as always @doowb and @jonschlinkert :smile:
